export const QUESTION_REQUEST_PENDING = 'QUESTION_REQUEST_PENDING';
export const QUESTION_REQUEST_SUCCESS = 'QUESTION_REQUEST_SUCCESS';
export const QUESTION_REQUEST_FAIL = 'QUESTION_REQUEST_FAIL';
export const GET_NEW_QUESTION = 'GET_NEW_QUESTION';
export const QUESTION_ANSWERED = 'QUESTION_ANSWERED';
